### ISSUE TITLE
Separate exit codes from test results

### ISSUE THREAD

**Issue by ifreecarve** [paypal/Illuminator#3]
Fix automator exit codes. Currently exit code is 0 only if automation succeeds with no failed tests. That is wrong. Exit code should be 0 every time automation process successfully runs (meaning finishes whatever we told him to) regardless of test results.

Few examples:
If we told automation to run tag with 5 tests and all 5 were ran, automation should return 0 regardless of failures.
If we told automation to run tag with 5 tests and only 4 were ran, automation should return some non 0 error code.
If we told automation to run tag with 0 tests and 0 were ran, automation should return 0 error code.
If we told automation to run tag with 0 tests and 2 were ran, automation should return some non 0 error code.
If automaton failed creating reports when reports are requested return non 0 exit code.

**Comment by ianfixes** [comment]
Closing in preparation for our V2 release (#99)
