### ISSUE TITLE
getconf ARG_MAX in ruby and pass it to javascript environment

### ISSUE THREAD

**Issue by ifreecarve** [paypal/Illuminator#60]
In Extensions.js when we write out files, we hard-code the ARG_MAX value into the code because it's fairly static.  But we shouldn't rely on that, and since it only needs to be done once per run we could save the extra second it would take (running a shell command in javascript) by running it in ruby instead and passing it into Environment.js.

**Comment by ianfixes** [comment]
Closing in preparation for our V2 release (#99) since Ruby and JavaScript are no longer parts of UI Automation
