### ISSUE TITLE
Add preferences for debugging options

### ISSUE THREAD

**Issue by ifreecarve** [paypal/Illuminator#7]
Add preferences for at least the following debugging options:
- String selectors
- module debug
  - AppMap
  - Automator
- messages about "will not run; test has step with unsupported implementation"
- info that gets printed on fail
  - list of visible elements
  - list of all elements
  - stack trace
- reports
  - coverage
  - selectorTimeCost

**Comment by ianfixes** [comment]
Closing in preparation for our V2 release (#99)
