### ISSUE TITLE
Unable to set configuration when building application

### ISSUE THREAD

**Issue by rgonzo** [paypal/Illuminator#84]
Currently there is no way to override the configuration setting that is set in the automation-builder.rb file. I would like to have an option to override the configuration setting.

**Comment by ifreecarve** [comment]
@kviksilver what are our options here?

**Comment by kviksilver** [comment]
We use our custom config only when calculating coverage, we could expose path parameter to end user...

**Comment by rgonzo** [comment]
sorry didnt mean to close the issue, I accidentally clicked the close button
